blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/zaherab/DQOPS_API/tree/main/docs
    about: Check the documentation for answers to common questions
  - name: Discussions
    url: https://github.com/zaherab/DQOPS_API/discussions
    about: Ask questions and discuss ideas in GitHub Discussions
